Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
a = np.zeros((3,3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
a = np.random.randint(1, 11, (5,5))
a

array([[ 6,  2,  2,  9,  5],
       [ 1,  9,  6,  3, 10],
       [10,  5, 10,  1,  3],
       [ 3,  7, 10,  5,  2],
       [ 4,  6,  5, 10,  8]])

Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
a= np.random.random((4,4))
a

array([[0.44213095, 0.60579846, 0.28042798, 0.39748895],
       [0.93317815, 0.35222296, 0.85868664, 0.25088146],
       [0.32330699, 0.16363641, 0.14101451, 0.77915807],
       [0.06028009, 0.22185884, 0.94221924, 0.73494129]])

Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
num_1= np.random.randint(1, 11, (5))
num_2= np.random.randint(1, 11, (5))
print(num_1 + num_2)
print(num_1 - num_2)
print(num_1 * num_2)
print(np.dot(num_1,num_2))

[12 20 11  2 12]
[-4  0 -9  0  4]
[ 32 100  10   1  32]
175


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
a= np.random.randint(1, 11, (7))
b= np.random.randint(1, 11, (7))
print(np.dot(a, b))

115


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
a= np.random.randint(1, 11, (2,2))
b= np.random.randint(1, 11, (2,3))  
print(np.dot(a,b))

[[ 46  96 104]
 [ 21  83  63]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
a= np.random.randint(1, 11, (2,2))
print(a)
print('\n')
print(np.linalg.inv(a))

[[7 4]
 [4 2]]


[[-1.   2. ]
 [ 2.  -3.5]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
a= np.random.random((4,4))
print(a)
print('\n')
print(a.T)

[[0.52081574 0.04009718 0.10505035 0.82900608]
 [0.62256354 0.0480739  0.2650502  0.93718366]
 [0.65839632 0.10272189 0.39032493 0.40819937]
 [0.5228063  0.32755261 0.70154684 0.65493814]]


[[0.52081574 0.62256354 0.65839632 0.5228063 ]
 [0.04009718 0.0480739  0.10272189 0.32755261]
 [0.10505035 0.2650502  0.39032493 0.70154684]
 [0.82900608 0.93718366 0.40819937 0.65493814]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
a= np.random.randint(1, 11, (3,4))
print(a)
b= np.random.randint(1, 11, (4))
print('\n')
print(b)
print('\n')
print(np.dot(a, b))

[[ 8  3  9 10]
 [10  1  7  5]
 [ 9  2  6  2]]


[ 6  3 10  8]


[227 173 136]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
a = np.random.random((2,3))
b= np.random.random(3)
print(a)
print('\n')
print(b)
print('\n')
print(np.dot(a, b))

[[0.25301783 0.74660673 0.35639887]
 [0.74232444 0.51106108 0.4563045 ]]


[0.86881644 0.94999127 0.88103324]


[1.24309518 1.53246668]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
a= np.random.randint(1, 11, (2,2))
print(a)
b= np.random.randint(1, 11, (2,2))
print('\n')
print(b)
print('\n')
print(a*b)

[[5 8]
 [9 7]]


[[10  9]
 [ 1  1]]


[[50 72]
 [ 9  7]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
a= np.random.randint(1, 11, (2,2))
print(a)
b= np.random.randint(1, 11, (2,2))
print('\n')
print(b)
print('\n')
print(f'{a*b} or {np.dot(a, b)}')


[[9 7]
 [1 8]]


[[4 4]
 [7 1]]


[[36 28]
 [ 7  8]] or [[85 43]
 [60 12]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
a= np.random.randint(1, 101, (5,5))
print(a)
print('\n')
print(a.sum())


[[48 80 78 39 10]
 [11 12 49 13 63]
 [52 14 15 32 92]
 [79  6 15 33 14]
 [79 50 80 22 62]]


1048


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
a= np.random.randint(1, 11, (4,4))
print(a)
b= np.random.randint(1, 11, (4,4))
print('\n')
print(b)
print('\n')
print(a-b)

[[ 3  9  6  6]
 [ 1  3  8  2]
 [ 8  2 10  7]
 [ 5  9 10  6]]


[[6 4 9 9]
 [8 4 3 9]
 [5 7 6 9]
 [5 8 6 5]]


[[-3  5 -3 -3]
 [-7 -1  5 -7]
 [ 3 -5  4 -2]
 [ 0  1  4  1]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
a= np.random.random((3,3))
print(a)
print('\n')
a_1=a[0, 0:].sum()
print('\n')
a_2=a[1,0:].sum()
a_3=a[2,0:].sum()

b= np.array([[a_1], [a_2], [a_3]])
print(b)



[[0.25538558 0.32401756 0.91625343]
 [0.44722914 0.6425683  0.88557342]
 [0.19782276 0.26127645 0.26021462]]




[[1.49565657]
 [1.97537086]
 [0.71931382]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
a= np.random.randint(1, 11, (3,4))
print(a)
print('\n')
print(a**2)

[[10  9  1  9]
 [10  4  7  6]
 [ 4  5  1  8]]


[[100  81   1  81]
 [100  16  49  36]
 [ 16  25   1  64]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
a= np.random.randint(1, 51, (4))
print(a)
print('\n')
print(a**0.5)

[26 25 35 45]


[5.09901951 5.         5.91607978 6.70820393]
